CALL usp_AddColumn('tblUserProfiles', 'phone_number', 'VARCHAR(15)', NULL, TRUE);
CALL usp_AddColumn('tblUserProfiles', 'gender', 'TINYINT', NULL, TRUE);
CALL usp_AddColumn('tblUserProfiles', 'date_of_birth', 'DATE', NULL, TRUE);
CALL usp_AddColumn('tblUserProfiles', 'address_line1', 'VARCHAR(255)', NULL, TRUE);
CALL usp_AddColumn('tblUserProfiles', 'address_line2', 'VARCHAR(255)', NULL, FALSE);
CALL usp_AddColumn('tblUserProfiles', 'region_id', 'BIGINT UNSIGNED', NULL, TRUE);
CALL usp_AddColumn('tblUserProfiles', 'country_id', 'BIGINT UNSIGNED', NULL, TRUE);
CALL usp_AddColumn('tblUserProfiles', 'city', 'VARCHAR(255)', NULL, TRUE);
CALL usp_AddColumn('tblUserProfiles', 'postal_code', 'VARCHAR(20)', NULL, TRUE);
CALL usp_AddColumn('tblUserProfiles', 'avatar_url', 'VARCHAR(512)', NULL, FALSE);
CALL usp_AddColumn('tblUserProfiles', 'user_id', 'BIGINT UNSIGNED', NULL, TRUE);