CALL usp_ResetAutoIncrement('tblCurrencies');

INSERT INTO `tblCurrencies`
(
    `iso_code`,
    `numeric_code`,
    `name`,
    `symbol`,
    `minor_unit`
)
VALUES
('AED', NULL, 'United Arab Emirates Dirham', 'د.إ', 2),
('AFN', NULL, 'Afghan Afghani', '؋', 2),
('ALL', NULL, 'Albanian Lek', 'Lek', 2),
('AMD', NULL, 'Armenian Dram', '֏', 2),
('AOA', NULL, 'Angolan Kwanza', 'Kz', 2),
('ARS', NULL, 'Argentine Peso', '$', 2),
('AUD', NULL, 'Australian Dollar', '$', 2),
('AWG', NULL, 'Aruban Florin', 'ƒ', 2),
('AZN', NULL, 'Azerbaijani Manat', '₼', 2),
('BAM', NULL, 'Bosnia and Herzegovina Convertible Mark', 'KM', 2),
('BBD', NULL, 'Barbados Dollar', '$', 2),
('BDT', NULL, 'Bangladeshi Taka', '৳', 2),
('BGN', NULL, 'Bulgarian Lev', 'лв', 2),
('BHD', NULL, 'Bahraini Dinar', 'د.ب', 3),
('BIF', NULL, 'Burundian Franc', 'FBu', 0),
('BMD', NULL, 'Bermudian Dollar', '$', 2),
('BND', NULL, 'Brunei Dollar', 'B$', 2),
('BOB', NULL, 'Bolivian Boliviano', 'Bs.', 2),
('BRL', NULL, 'Brazilian Real', 'R$', 2),
('BSD', NULL, 'Bahamian Dollar', 'B$', 2),
('BTN', NULL, 'Bhutanese Ngultrum', 'Nu.', 2),
('BWP', NULL, 'Botswana Pula', 'P', 2),
('BYN', NULL, 'Belarusian Ruble', 'Br', 2),
('BZD', NULL, 'Belize Dollar', 'BZ$', 2),
('CAD', NULL, 'Canadian Dollar', 'C$', 2),
('CDF', NULL, 'Congolese Franc', 'FC', 2),
('CHF', NULL, 'Swiss Franc', 'CHF', 2),
('CLP', NULL, 'Chilean Peso', '$', 0),
('CNY', NULL, 'Chinese Yuan', '¥', 2),
('COP', NULL, 'Colombian Peso', '$', 2),
('CRC', NULL, 'Costa Rican Colón', '₡', 2),
('CUC', NULL, 'Cuban Convertible Peso', 'CUC$', 2),
('CUP', NULL, 'Cuban Peso', '₱', 2),
('CVE', NULL, 'Cape Verdean Escudo', '$', 2),
('CZK', NULL, 'Czech Koruna', 'Kč', 2),
('DJF', NULL, 'Djiboutian Franc', 'Fdj', 0),
('DKK', NULL, 'Danish Krone', 'kr', 2),
('DOP', NULL, 'Dominican Peso', 'RD$', 2),
('DZD', NULL, 'Algerian Dinar', 'د.ج', 2),
('EGP', NULL, 'Egyptian Pound', 'E£', 2),
('ERN', NULL, 'Eritrean Nakfa', 'Nfk', 2),
('ETB', NULL, 'Ethiopian Birr', 'Br', 2),
('EUR', NULL, 'Euro', '€', 2),
('FJD', NULL, 'Fiji Dollar', '$', 2),
('FKP', NULL, 'Falkland Islands Pound', '£', 2),
('GBP', NULL, 'Pound Sterling', '£', 2),
('GEL', NULL, 'Georgian Lari', '₾', 2),
('GHS', NULL, 'Ghanaian Cedi', '₵', 2),
('GIP', NULL, 'Gibraltar Pound', '£', 2),
('GMD', NULL, 'Gambian Dalasi', 'D', 2),
('GNF', NULL, 'Guinean Franc', 'FG', 0),
('GTQ', NULL, 'Guatemalan Quetzal', 'Q', 2),
('GYD', NULL, 'Guyanese Dollar', '$', 2),
('HKD', NULL, 'Hong Kong Dollar', 'HK$', 2),
('HNL', NULL, 'Honduran Lempira', 'L', 2),
('HRK', NULL, 'Croatian Kuna', 'kn', 2),
('HTG', NULL, 'Haitian Gourde', 'G', 2),
('HUF', NULL, 'Hungarian Forint', 'Ft', 2),
('IDR', NULL, 'Indonesian Rupiah', 'Rp', 2),
('ILS', NULL, 'Israeli New Shekel', '₪', 2),
('INR', NULL, 'Indian Rupee', '₹', 2),
('IQD', NULL, 'Iraqi Dinar', 'ع.د', 3),
('IRR', NULL, 'Iranian Rial', '﷼', 2),
('ISK', NULL, 'Icelandic Króna', 'kr', 0),
('JMD', NULL, 'Jamaican Dollar', 'J$', 2),
('JOD', NULL, 'Jordanian Dinar', 'د.ا', 3),
('JPY', NULL, 'Japanese Yen', '¥', 0),
('KES', NULL, 'Kenyan Shilling', 'KSh', 2),
('KGS', NULL, 'Kyrgyzstani Som', 'с', 2),
('KHR', NULL, 'Cambodian Riel', '៛', 2),
('KMF', NULL, 'Comorian Franc', 'CF', 0),
('KPW', NULL, 'North Korean Won', '₩', 2),
('KRW', NULL, 'South Korean Won', '₩', 0),
('KWD', NULL, 'Kuwaiti Dinar', 'د.ك', 3),
('KYD', NULL, 'Cayman Islands Dollar', '$', 2),
('KZT', NULL, 'Kazakhstani Tenge', '〒', 2),
('LAK', NULL, 'Lao Kip', '₭', 2),
('LBP', NULL, 'Lebanese Pound', 'ل.ل', 2),
('LKR', NULL, 'Sri Lankan Rupee', '₨', 2),
('LRD', NULL, 'Liberian Dollar', 'L$', 2),
('LSL', NULL, 'Lesotho Loti', 'L', 2),
('LYD', NULL, 'Libyan Dinar', 'ل.د', 3),
('MAD', NULL, 'Moroccan Dirham', 'د.م.', 2),
('MDL', NULL, 'Moldovan Leu', 'L', 2),
('MGA', NULL, 'Malagasy Ariary', 'Ar', 2),
('MKD', NULL, 'Macedonian Denar', 'ден', 2),
('MMK', NULL, 'Burmese Kyat', 'Ks', 2),
('MNT', NULL, 'Mongolian Tögrög', '₮', 2),
('MOP', NULL, 'Macanese Pataca', 'P', 2),
('MRU', NULL, 'Mauritanian Ouguiya', 'UM', 2),
('MUR', NULL, 'Mauritian Rupee', '₨', 2),
('MVR', NULL, 'Maldivian Rufiyaa', 'MVR', 2),
('MWK', NULL, 'Malawian Kwacha', 'MK', 2),
('MXN', NULL, 'Mexican Peso', '$', 2),
('MYR', NULL, 'Malaysian Ringgit', 'RM', 2),
('MZN', NULL, 'Mozambican Metical', 'MT', 2),
('NAD', NULL, 'Namibian Dollar', 'N$', 2),
('NGN', NULL, 'Nigerian Naira', '₦', 2),
('NIO', NULL, 'Nicaraguan Córdoba', 'C$', 2),
('NOK', NULL, 'Norwegian Krone', 'kr', 2),
('NPR', NULL, 'Nepalese Rupee', '₨', 2),
('NZD', NULL, 'New Zealand Dollar', 'NZ$', 2),
('OMR', NULL, 'Omani Rial', 'ر.ع.', 3),
('PAB', NULL, 'Panamanian Balboa', 'B/.', 2),
('PEN', NULL, 'Peruvian Sol', 'S/.', 2),
('PGK', NULL, 'Papua New Guinean Kina', 'K', 2),
('PHP', NULL, 'Philippine Peso', '₱', 2),
('PKR', NULL, 'Pakistani Rupee', '₨', 2),
('PLN', NULL, 'Polish Złoty', 'zł', 2),
('PYG', NULL, 'Paraguayan Guaraní', '₲', 0),
('QAR', NULL, 'Qatari Riyal', 'ر.ق', 2),
('RON', NULL, 'Romanian Leu', 'L', 2),
('RSD', NULL, 'Serbian Dinar', 'дин', 2),
('RUB', NULL, 'Russian Ruble', '₽', 2),
('RWF', NULL, 'Rwandan Franc', 'Fr', 0),
('SAR', NULL, 'Saudi Riyal', 'ر.س', 2),
('SBD', NULL, 'Solomon Islands Dollar', '$', 2),
('SCR', NULL, 'Seychellois Rupee', '₨', 2),
('SDG', NULL, 'Sudanese Pound', 'ج.س.', 2),
('SEK', NULL, 'Swedish Krona', 'kr', 2),
('SGD', NULL, 'Singapore Dollar', 'S$', 2),
('SHP', NULL, 'Saint Helena Pound', '£', 2),
('SLE', NULL, 'Sierra Leonean Leone', 'Le', 2),
('SOS', NULL, 'Somali Shilling', 'Sh.So.', 2),
('SRD', NULL, 'Surinamese Dollar', '$', 2),
('SSP', NULL, 'South Sudanese Pound', '£', 2),
('STN', NULL, 'São Tomé and Príncipe Dobra', 'Db', 2),
('SVC', NULL, 'Salvadoran Colón', '₡', 2),
('SYP', NULL, 'Syrian Pound', '£', 2),
('SZL', NULL, 'Swazi Lilangeni', 'L', 2),
('THB', NULL, 'Thai Baht', '฿', 2),
('TJS', NULL, 'Tajikistani Somoni', 'ЅМ', 2),
('TMT', NULL, 'Turkmenistan Manat', 'm', 2),
('TND', NULL, 'Tunisian Dinar', 'د.ت', 3),
('TOP', NULL, 'Tongan Paʻanga', 'T$', 2),
('TRY', NULL, 'Turkish Lira', '₺', 2),
('TTD', NULL, 'Trinidad and Tobago Dollar', 'TT$', 2),
('TWD', NULL, 'New Taiwan Dollar', 'NT$', 2),
('TZS', NULL, 'Tanzanian Shilling', 'TSh', 2),
('UAH', NULL, 'Ukrainian Hryvnia', '₴', 2),
('UGX', NULL, 'Ugandan Shilling', 'Sh', 0),
('USD', NULL, 'United States Dollar', '$', 2),
('UYU', NULL, 'Uruguayan Peso', '$', 2),
('UZS', NULL, 'Uzbekistani Soʻm', 'лв', 2),
('VED', NULL, 'Venezuelan Bolívar', 'Bs.S', 2),
('VND', NULL, 'Vietnamese Đồng', '₫', 0),
('VUV', NULL, 'Vanuatu Vatu', 'VT', 0),
('WST', NULL, 'Samoan Tala', 'T$', 2),
('XAF', NULL, 'Central African CFA Franc', 'FCFA', 0),
('XCD', NULL, 'East Caribbean Dollar', 'EC$', 2),
('XOF', NULL, 'West African CFA Franc', 'CFA', 0),
('XPF', NULL, 'CFP Franc', '₣', 0),
('YER', NULL, 'Yemeni Rial', '﷼', 2),
('ZAR', NULL, 'South African Rand', 'R', 2),
('ZMW', NULL, 'Zambian Kwacha', 'ZK', 2),
('ZWL', NULL, 'Zimbabwean Dollar', 'ZWL$', 2);

SELECT 'tblCurrencies data inserted successfully.' AS message;