TRUNCATE TABLE `tblCurrencies`;
ALTER TABLE `tblCurrencies` AUTO_INCREMENT = 1;
INSERT INTO `tblCurrencies`
(`iso_code`, `numeric_code`, `name`, `symbol`, `minor_unit`)
VALUES
('AED', '784', 'United Arab Emirates Dirham', 'د.إ.', 2),
('AFN', '971', 'Afghan Afghani', 'Af', 2),
('ALL', '008', 'Albanian Lek', 'L', 2),
('AMD', '051', 'Armenian Dram', '֏', 2),
('ANG', '532', 'Netherlands Antillean Guilder', 'ƒ', 2),
('AOA', '973', 'Angolan Kwanza', 'Kz', 2),
('ARS', '032', 'Argentine Peso', 'AR$', 2),
('AUD', '036', 'Australian Dollar', 'AU$', 2),
('AWG', '533', 'Aruban Florin', 'ƒ', 2),
('AZN', '944', 'Azerbaijani Manat', 'ман', 2),
('BAM', '977', 'Bosnia and Herzegovina Convertible Mark', 'KM', 2),
('BBD', '052', 'Barbadian Dollar', 'BBD$', 2),
('BDT', '050', 'Bangladeshi Taka', '৳', 2),
('BGN', '975', 'Bulgarian Lev', 'лв.', 2),
('BHD', '048', 'Bahraini Dinar', 'BD', 3),
('BIF', '108', 'Burundian Franc', 'FBu', 0),
('BMD', '060', 'Bermudian Dollar', '$', 2),
('BND', '096', 'Brunei Dollar', 'B$', 2),
('BOB', '068', 'Bolivian Boliviano', 'Bs.', 2),
('BRL', '986', 'Brazilian Real', 'R$', 2),
('BSD', '044', 'Bahamian Dollar', '$', 2),
('BTN', '064', 'Bhutanese Ngultrum', 'Nu.', 2),
('BWP', '072', 'Botswana Pula', 'P', 2),
('BYN', '933', 'Belarusian Ruble', 'Br', 2),
('BZD', '084', 'Belize Dollar', 'BZ$', 2),
('CAD', '124', 'Canadian Dollar', 'CA$', 2),
('CDF', '976', 'Congolese Franc', 'FC', 2),
('CHF', '756', 'Swiss Franc', 'Fr.', 2),
('CLP', '152', 'Chilean Peso', 'CL$', 0),
('CNY', '156', 'Chinese Yuan', 'CN¥', 2),
('COP', '170', 'Colombian Peso', 'CO$', 2),
('CRC', '188', 'Costa Rican Colon', '₡', 2),
('CUC', '931', 'Cuban convertible Peso', 'CUC$', 2),
('CUP', '192', 'Cuban Peso', '$MN', 2),
('CVE', '132', 'Cabo Verdean Escudo', 'CV$', 2),
('CZK', '203', 'Czech Koruna', 'Kč', 2),
('DJF', '262', 'Djiboutian Franc', 'Fdj', 0),
('DKK', '208', 'Danish Krone', 'kr.', 2),
('DOP', '214', 'Dominican Peso', 'RD$', 2),
('DZD', '012', 'Algerian Dinar', 'DA', 2),
('EGP', '818', 'Egyptian Pound', 'E£', 2),
('ERN', '232', 'Eritrean Nakfa', 'Nkf', 2),
('ETB', '230', 'Ethiopian Birr', 'Br', 2),
('EUR', '978', 'Euro', '€', 2),
('FJD', '242', 'Fijian Dollar', 'FJ$', 2),
('FKP', '238', 'Falkland Islands Pound', 'FK£', 2),
('GBP', '826', 'Pound Sterling', '£', 2),
('GEL', '981', 'Georgian Lari', '₾', 2),
('GHS', '936', 'Ghanaian Cedi', 'GH₵', 2),
('GIP', '292', 'Gibraltar Pound', '£', 2),
('GMD', '270', 'Gambian Dalasi', 'D', 2),
('GNF', '324', 'Guinean Franc', 'FG', 0),
('GTQ', '320', 'Guatemalan Quetzal', 'Q', 2),
('GYD', '328', 'Guyanese Dollar', 'G$', 2),
('HKD', '344', 'Hong Kong Dollar', 'HK$', 2),
('HNL', '340', 'Honduran Lempira', 'L', 2),
('HRK', '191', 'Croatian Kuna', 'kn', 2),
('HTG', '332', 'Haitian Gourde', 'G', 2),
('HUF', '348', 'Hungarian Forint', 'Ft', 2),
('IDR', '360', 'Indonesian Rupiah', 'Rp', 2),
('ILS', '376', 'Israeli new Shekel', '₪', 2),
('INR', '356', 'Indian Rupee', 'Rs.', 2),
('IQD', '368', 'Iraqi Dinar', 'د.ع.', 3),
('IRR', '364', 'Iranian Rial', '﷼', 2),
('ISK', '352', 'Icelandic Krona', 'kr', 0),
('JMD', '388', 'Jamaican Dollar', 'J$', 2),
('JOD', '400', 'Jordanian Dinar', 'JD', 3),
('JPY', '392', 'Japanese Yen', '¥', 0),
('KES', '404', 'Kenyan Shilling', 'KSh', 2),
('KGS', '417', 'Kyrgyzstani Som', 'с', 2),
('KHR', '116', 'Cambodian Riel', '៛', 2),
('KMF', '174', 'Comorian Franc', 'CF', 0),
('KPW', '408', 'North Korean Won', '₩', 2),
('KRW', '410', 'South Korean Won', '₩', 0),
('KWD', '414', 'Kuwaiti Dinar', 'KD', 3),
('KYD', '136', 'Cayman Islands Dollar', 'CI$', 2),
('KZT', '398', 'Kazakhstani Tenge', '₸', 2),
('LAK', '418', 'Lao Kip', '₭N', 2),
('LBP', '422', 'Lebanese Pound', 'LL.', 2),
('LKR', '144', 'Sri Lankan Rupee', 'Rs.', 2),
('LRD', '430', 'Liberian Dollar', 'L$', 2),
('LSL', '426', 'Lesotho Loti', 'L', 2),
('LYD', '434', 'Libyan Dinar', 'LD', 3),
('MAD', '504', 'Moroccan Dirham', 'DH', 2),
('MDL', '498', 'Moldovan Leu', 'L', 2),
('MGA', '969', 'Malagasy Ariary', 'Ar', 2),
('MKD', '807', 'Macedonian Denar', 'den', 2),
('MMK', '104', 'Myanmar Kyat', 'Ks', 2),
('MNT', '496', 'Mongolian Tögrög', '₮', 2),
('MOP', '446', 'Macanese Pataca', 'MOP$', 2),
('MRU', '929', 'Mauritanian Ouguiya', 'UM', 2),
('MUR', '480', 'Mauritian Rupee', 'Rs.', 2),
('MVR', '462', 'Maldivian Rufiyaa', 'MRf', 2),
('MWK', '454', 'Malawian Kwacha', 'MK', 2),
('MXN', '484', 'Mexican Peso', 'MX$', 2),
('MYR', '458', 'Malaysian Ringgit', 'RM', 2),
('MZN', '943', 'Mozambican Metical', 'MTn', 2),
('NAD', '516', 'Namibian Dollar', 'N$', 2),
('NGN', '566', 'Nigerian Naira', '₦', 2),
('NIO', '558', 'Nicaraguan Córdoba', 'C$', 2),
('NOK', '578', 'Norwegian Krone', 'kr', 2),
('NPR', '524', 'Nepalese Rupee', 'Rs.', 2),
('NZD', '554', 'New Zealand Dollar', 'NZ$', 2),
('OMR', '512', 'Omani Rial', 'OR', 3),
('PAB', '590', 'Panamanian Balboa', 'B/.', 2),
('PEN', '604', 'Peruvian Sol', 'S/.', 2),
('PGK', '598', 'Papua New Guinean Kina', 'K', 2),
('PHP', '608', 'Philippine Peso', '₱', 2),
('PKR', '586', 'Pakistani Rupee', 'Rs.', 2),
('PLN', '985', 'Polish Zloty', 'zł', 2),
('PYG', '600', 'Paraguayan Guaraní', '₲', 0),
('QAR', '634', 'Qatari Riyal', 'QR', 2),
('RON', '946', 'Romanian Leu', 'L', 2),
('RSD', '941', 'Serbian Dinar', 'din', 2),
('RUB', '643', 'Russian Ruble', '₽', 2),
('RWF', '646', 'Rwandan Franc', 'FRw', 0),
('SAR', '682', 'Saudi Riyal', 'SR', 2),
('SBD', '090', 'Solomon Islands Dollar', 'SI$', 2),
('SCR', '690', 'Seychellois Rupee', 'Rs.', 2),
('SDG', '938', 'Sudanese Pound', '£SD', 2),
('SEK', '752', 'Swedish Krona', 'kr', 2),
('SGD', '702', 'Singapore Dollar', 'S$', 2),
('SHP', '654', 'Saint Helena Pound', '£', 2),
('SLL', '694', 'Sierra Leonean Leone', 'Le', 2),
('SOS', '706', 'Somali Shilling', 'Sh.So.', 2),
('SRD', '968', 'Surinamese Dollar', 'Sr$', 2),
('SSP', '728', 'South Sudanese Pound', 'SS£', 2),
('STN', '930', 'Sao Tome and Príncipe Dobra', 'Db', 2),
('SVC', '222', 'Salvadoran Colón', '₡', 2),
('SYP', '760', 'Syrian Pound', 'LS', 2),
('SZL', '748', 'Swazi Lilangeni', 'L', 2),
('THB', '764', 'Thai Baht', '฿', 2),
('TJS', '972', 'Tajikistani Somoni', 'SM', 2),
('TMT', '934', 'Turkmenistan Manat', 'm.', 2),
('TND', '788', 'Tunisian Dinar', 'DT', 3),
('TOP', '776', 'Tongan Paʻanga', 'T$', 2),
('TRY', '949', 'Turkish Lira', 'TL', 2),
('TTD', '780', 'Trinidad and Tobago Dollar', 'TT$', 2),
('TWD', '901', 'New Taiwan Dollar', 'NT$', 2),
('TZS', '834', 'Tanzanian Shilling', 'TSh', 2),
('UAH', '980', 'Ukrainian Hryvnia', '₴', 2),
('UGX', '800', 'Ugandan Shilling', 'USh', 0),
('USD', '840', 'United States Dollar', '$', 2),
('UYU', '858', 'Uruguayan Peso', '$U', 2),
('UZS', '860', 'Uzbekistani Som', 'сум', 2),
('VES', '928', 'Venezuelan Bolívar Soberano', 'Bs.F', 2),
('VND', '704', 'Vietnamese Dong', '₫', 0),
('VUV', '548', 'Vanuatu Vatu', 'VT', 0),
('WST', '882', 'Samoan Tala', 'T', 2),
('XAF', '950', 'Central African CFA Franc BEAC', 'Fr', 0),
('XCD', '951', 'East Caribbean Dollar', '$', 2),
('XOF', '952', 'West African CFA Franc BCEAO', '₣', 0),
('XPF', '953', 'CFP Franc (Franc Pacifique)', '₣', 0),
('YER', '886', 'Yemeni Rial', 'YR', 2),
('ZAR', '710', 'South African Rand', 'R', 2),
('ZMW', '967', 'Zambian Kwacha', 'ZK', 2),
('ZWL', '932', 'Zimbabwean Dollar', 'Z$', 2);