name: MySQL Syntax Check

on:
  pull_request:
    paths:
      - "**/*.sql"
  push:
    paths:
      - "**/*.sql"

jobs:
  mysql-syntax-check:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to start..."
          for i in {1..30}; do
            mysql -h 127.0.0.1 -uroot -proot -e "SELECT 1" && break
            sleep 2
          done

      - name: Validate SQL files
        run: |
          for f in $(find . -name "*.sql"); do
            echo "Checking syntax for $f"
            mysql -h 127.0.0.1 -uroot -proot test_db < "$f"
          done
