name: MySQL Syntax Check

on:
  pull_request:
    paths:
      - "**/*.sql"
  push:
    paths:
      - "**/*.sql"

jobs:
  mysql-syntax-check:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to start..."
          for i in {1..30}; do
            mysql -h 127.0.0.1 -uroot -proot -e "SELECT 1" && break
            sleep 2
          done

      - name: Install PowerShell
        run: |
          sudo apt-get update
          sudo apt-get install -y powershell

      # --- BASELINE CHECK --- #
      - name: Checkout base code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha || github.event.before }}

      - name: List files on Base
        run: ls -lA

      - name: Check for base migration files
        id: check-base-files
        run: |
          if [ -f "Run-Migration.ps1" ] && [ -d "src" ] && [ -f "src/dependencies.json" ]; then
            echo "files_exist=true" >> $GITHUB_OUTPUT
          else
            echo "files_exist=false" >> $GITHUB_OUTPUT
          fi

      - name: Run Migration on Base
        if: steps.check-base-files.outputs.files_exist == 'true'
        run: pwsh -File ./Run-Migration.ps1 -db test_db

      - name: Validate Base SQL
        if: steps.check-base-files.outputs.files_exist == 'true'
        id: validate-base
        continue-on-error: true
        run: mysql -h 127.0.0.1 -uroot -proot test_db < "output.sql"

      # --- HEAD CHECK --- #
      - name: Checkout Head Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0 # To allow git diff later

      - name: List files on Head
        run: ls -lA

      - name: Run Migration on Head
        run: pwsh -File ./Run-Migration.ps1 -db test_db

      - name: Validate Head SQL
        id: validate-head
        continue-on-error: true
        run: mysql -h 127.0.0.1 -uroot -proot test_db < "output.sql"

      # --- DECISION & REPORTING --- #
      - name: Analyze and Report
        if: always()
        run: |
          echo "Baseline validation status: ${{ steps.validate-base.outcome }}"
          echo "HEAD validation status: ${{ steps.validate-head.outcome }}"

          # If the base validation was skipped, it means the migration files weren't there.
          # In this case, we treat the baseline as 'success' for the purpose of comparison.
          if ( [ "${{ steps.validate-base.outcome }}" == "success" ] || [ "${{ steps.validate-base.outcome }}" == "skipped" ] || [ "${{ steps.validate-base.outcome }}" == "" ] ) && [ "${{ steps.validate-head.outcome }}" == "failure" ]; then
            echo "::error::A syntax error was introduced in this commit."
            
            echo "The failure is likely caused by changes in one of the following files:"
            if [ "${{ github.event_name }}" == "pull_request" ]; then
              FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '\.sql || true)
            else
              FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.sql || true)
            fi
            echo "$FILES"
            
            exit 1
          elif [ "${{ steps.validate-base.outcome }}" == "failure" ]; then
            echo "::warning::Syntax check failed, but the error was already present in the base commit. The workflow will not be failed."
          elif [ "${{ steps.validate-head.outcome }}" == "success" ]; then
            echo "SQL syntax check passed."
          else
            # This case handles when both pass, or when base fails and head is skipped (which shouldn't happen).
            echo "No new errors detected. Base status: ${{ steps.validate-base.outcome }}, Head status: ${{ steps.validate-head.outcome }}"
          fi
