name: SQLFluff Lint

on:
  pull_request:
    paths:
      - "**/*.sql"
  push:
    paths:
      - "**/*.sql"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SQLFluff
        run: pip install sqlfluff

      - name: Lint SQL files
        run: sqlfluff lint . --dialect mysql --templater jinja
