name: SQLFluff Lint

on:
  pull_request:
    paths:
      - "**/*.sql"
  push:
    paths:
      - "**/*.sql"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SQLFluff
        run: pip install sqlfluff

      - name: Preprocess SQL files
        run: |
          # Delete lines starting with DELIMITER
          find . -name "*.sql" -exec sed -i '/^DELIMITER/d' {} \;
          # Replace $$ with ;
          find . -name "*.sql" -exec sed -i 's/\$\$/;/g' {} \;

      - name: Lint SQL files
        run: sqlfluff lint . --dialect mysql --templater jinja
